

FROM python:3.13-slim

WORKDIR /app


RUN apt-get update && apt-get install -y \
    default-libmysqlclient-dev \
    pkg-config \
    gcc \
    && rm -rf /var/lib/apt/lists/*


COPY requirements.txt .


RUN pip install --no-cache-dir -r requirements.txt


COPY . .


RUN mkdir -p /app/staticfiles


EXPOSE 8000


CMD ["sh", "-c", "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn jobboard.wsgi:application --bind 0.0.0.0:8000 --workers 2"]
