# Generated by Django 6.0.6 on 2026-06-18 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_notification"),
        ("jobs", "0004_company_company_size_company_founded_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="jobs.application",
            ),
        ),
    ]
