# Generated by Django 6.0.6 on 2026-06-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_notification_application"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="skills",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
